// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Yj7WROYfqWrM3sbTlzsDCfWM5LVFp_s',
    appId: '1:824800689402:web:4f0e79bc7d803dedf75d43',
    messagingSenderId: '824800689402',
    projectId: 'fesbat-b59dd',
    authDomain: 'fesbat-b59dd.firebaseapp.com',
    storageBucket: 'fesbat-b59dd.appspot.com',
    measurementId: 'G-XGE21Q0VHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOkFNgdZXF3Mox6ncf_WYd1Ph8rmc4xok',
    appId: '1:824800689402:android:030df839779917bef75d43',
    messagingSenderId: '824800689402',
    projectId: 'fesbat-b59dd',
    storageBucket: 'fesbat-b59dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-6QPaqQsBhgB6Lq8O8ac0ngRlUg1MU0',
    appId: '1:824800689402:ios:137fc90535740815f75d43',
    messagingSenderId: '824800689402',
    projectId: 'fesbat-b59dd',
    storageBucket: 'fesbat-b59dd.appspot.com',
    androidClientId: '824800689402-jgb5gum59pueh6a4q5jci0si3sm2mlhd.apps.googleusercontent.com',
    iosBundleId: 'com.festusjaphet.rmfabric',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI-6QPaqQsBhgB6Lq8O8ac0ngRlUg1MU0',
    appId: '1:824800689402:ios:137fc90535740815f75d43',
    messagingSenderId: '824800689402',
    projectId: 'fesbat-b59dd',
    storageBucket: 'fesbat-b59dd.appspot.com',
    androidClientId: '824800689402-jgb5gum59pueh6a4q5jci0si3sm2mlhd.apps.googleusercontent.com',
    iosBundleId: 'com.festusjaphet.rmfabric',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJO0CJneKHEmHpIpv9iB9zMPttncSTkyE',
    appId: '1:824800689402:web:d5fdbc5443c5b7d2f75d43',
    messagingSenderId: '824800689402',
    projectId: 'fesbat-b59dd',
    authDomain: 'fesbat-b59dd.firebaseapp.com',
    storageBucket: 'fesbat-b59dd.appspot.com',
    measurementId: 'G-9M066GSE5F',
  );

}